using Acrelec.SCO.Core.Helpers;
using Acrelec.SCO.Core.Interfaces;
using Acrelec.SCO.Core.Managers;
using Acrelec.SCO.Core.Providers;
using Acrelec.SCO.DataStructures;
using System;
using System.Threading.Tasks;

namespace Acrelec.SCO.Core
{
    public class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("SCO - Self Check Out System");

            //init
            IItemsProvider itemsProvider = new ItemsProvider();
            IOrderManager orderManager = new OrderManager(itemsProvider);

            //list POS items
            ListAllItems(itemsProvider);

            //todo - check if server is available for order injection

            //todo - create an order containing the following items:
            //1*Coke
            //2*Water
            var newOrder = new Order();

            //...            

            //inject the order to POS
            var assignedOrderNumber = await orderManager.InjectOrderAsync(newOrder);

            if (string.IsNullOrEmpty(assignedOrderNumber) == true)
                Console.WriteLine("Order injected with success");
            else
                Console.WriteLine("Error injecting order");

            Console.ReadLine();
        }

        /// <summary>
        /// list in Console all items (with all their properties)
        /// </summary>
        private static void ListAllItems(IItemsProvider itemsProvider)
        {
            //todo - list items and for each item a short code generated by the POSItemExtensions
            Console.WriteLine("----List All Items ----");
            for (int i = 0; i < itemsProvider.AllPOSItems.Count; i++)
            {
                Console.WriteLine($"Item {i}: ItemCode:{itemsProvider.AllPOSItems[i].ItemCode}, " +
                    $"Name:{itemsProvider.AllPOSItems[i].Name}, " +
                    $"ShortName:{itemsProvider.AllPOSItems[i].GetShortName()}, " +
                    $"IsAvailable:{itemsProvider.AllPOSItems[i].IsAvailable}, " +
                    $"UnitPrice:{itemsProvider.AllPOSItems[i].IsAvailable}");
            }
            Console.WriteLine("------------------------");
        }
    }
}
